import Locker from "@/components/Locker";
import Status from "@/components/Status";

const data = {
  faculty: "FIC",
  lockers: [
    {
      letter: "A",
      location:
        "Por Vergara, al lado izquierdo de la sala del Centro de Estudiantes.",
      slots: [
        {
          number: 1,
          status: true,
          student: "Alexander Vargas",
          career: "OC",
          mail: "natalia.cassaretto",
          phone: 57369481,
        },
        {
          number: 2,
          status: true,
          student: "Joaquin Humberto",
          career: "OC",
          mail: "joaquin.jimenez",
          phone: 57369481,
        },
        {
          number: 3,
          status: true,
          student: "Lucas Villaseca",
          career: "OC",
          mail: "lucas.villaseca_c@mail.udp.cl",
          phone: 63727008,
        },
        {
          number: 4,
          status: true,
          student: "Felipe Vargas Diaz",
          career: "OC",
          mail: "felipe.vargas@mail.udp.cl",
          phone: 56978796762,
        },
        {
          number: 5,
          status: true,
          student: "Canelita",
          career: "PC",
          mail: "admin@udp.cl",
          phone: 56912345678,
        },
        {
          number: 6,
          status: true,
          student: "Barbara Macias",
          career: "OC",
          mail: "barbara.macias@mail.udp.cl",
          phone: 56935137599,
        },
        {
          number: 7,
          status: true,
          student: "Maria de los angeles Martinez",
          career: "TI",
          mail: "maria.martinez9@mail.udp.cl",
          phone: 56966333232,
        },
        {
          number: 8,
          status: true,
          student: "Bastian Villarroel",
          career: "OC",
          mail: "bastian.villarroel@mail.udp.cl",
          phone: 56940379686,
        },
        {
          number: 9,
          status: true,
          student: "Matias Miranda",
          career: "ICI",
          mail: "matias.miranda2@mail.udp.cl",
          phone: 56981635333,
        },
        {
          number: 10,
          status: true,
          student: "Felipe Cayuman",
          career: "ICI",
          mail: "felipe.cayuman_r",
          phone: 56979518414,
        },
        {
          number: 11,
          status: true,
          student: "Fernando Espinoza",
          career: "ICI",
          mail: "fernando.espinoza",
          phone: 56993533464,
        },
        {
          number: 12,
          status: true,
          student: "Daniela Nova",
          career: "ICI",
          mail: "daniela.nova",
          phone: 56962031830,
        },
        {
          number: 13,
          status: true,
          student: "Maria Paz Ibañez",
          career: "ICI",
          mail: "maria.ibanez@mail.udp.cl",
          phone: 56945252238,
        },
        {
          number: 14,
          status: true,
          student: "Michelle Ramirez",
          career: "TI",
          mail: "michelle.ramirez@mail.udp.cl",
          phone: 56972600465,
        },
        {
          number: 15,
          status: true,
          student: "Eric Fernandez",
          career: "ICI",
          mail: "eric.fernandez@mail.udp.cl",
          phone: 56922587913,
        },
      ],
    },
    {
      letter: "B",
      location: "Por Ejercito, segundo piso, al fondo.",
      slots: [
        {
          number: 1,
          status: true,
          student: "Anghelo Ferrada",
          career: "ICI",
          mail: "anghelo.ferrada@mail.udp.cl",
          phone: 56930723396,
        },
        {
          number: 2,
          status: true,
          student: "Barbara Rojas",
          career: "OC",
          mail: "barbara.rojas2@mail.udp.cl",
          phone: 56976719402,
        },
        {
          number: 3,
          status: true,
          student: "Catalina Diaz",
          career: "ICI",
          mail: "catalina.diaz7@mail.udp.cl",
          phone: 569,
        },
        {
          number: 4,
          status: true,
          student: "Esteban Chavez",
          career: "OC",
          mail: "esteban.chavez@mail.udp.cl",
          phone: 56941559757,
        },
        {
          number: 5,
          status: true,
          student: "Mateo Morales",
          career: "ICI",
          mail: "mateo.morales@mail.udp.cl",
          phone: 56947854579,
        },
        {
          number: 6,
          status: true,
          student: "Pamela Castro",
          career: "ICI",
          mail: "pamela.castro_l@mail.udp.cl",
          phone: 56951489352,
        },
        {
          number: 7,
          status: true,
          student: "Conny Diaz",
          career: "ICI",
          mail: "conny.diaz_a@mail.udp.cl",
          phone: 56967126169,
        },
        {
          number: 8,
          status: true,
          student: "Catalina Diaz",
          career: "ICI",
          mail: "catalina.diaz7@mail.udp.cl",
          phone: 56990337065,
        },
        {
          number: 9,
          status: true,
          student: "Natalia Cassaretto",
          career: "ICI",
          mail: "natalia.cassaretto",
          phone: 56920644853,
        },
        {
          number: 10,
          status: true,
          student: "Daniel Miranda",
          career: "TI",
          mail: "daniel.miranda2@mail.udp.cl",
          phone: 56930037275,
        },
        {
          number: 11,
          status: true,
          student: "Ghislaine Garcia",
          career: "OC",
          mail: "ghislaine.garcia_fe@mail.udp.cl",
          phone: 56945083052,
        },
        {
          number: 12,
          status: true,
          student: "Alenjandro Beltrán",
          career: "ICI",
          mail: "alejandro.beltran@mail.udp.cl",
          phone: 56949034133,
        },
        {
          number: 13,
          status: true,
          student: "Mauricio Camblor",
          career: "ICI",
          mail: "mauricio.camblor@mail.udp.cl",
          phone: 56991704528,
        },
        {
          number: 14,
          status: true,
          student: "Rita Diaz",
          career: "ICI",
          mail: "rita.diaz@mail.udp.cl",
          phone: 56973473102,
        },
        {
          number: 15,
          status: true,
          student: "Javiera Ferreira",
          career: "ICI",
          mail: "javiera.ferreira1@mail.udp.cl",
          phone: 56963608459,
        },
      ],
    },
    {
      letter: "C",
      location: "Por Ejercito, segundo piso, al fondo.",
      slots: [
        {
          number: 1,
          status: true,
          student: "Scarlett Torres",
          career: "OC",
          mail: "scarlett.torres@mail.udp.cl",
          phone: 56957176703,
        },
        {
          number: 2,
          status: true,
          student: "Maximiliano Oliva",
          career: "TI",
          mail: "maximiliano.oliva@mail.udp.cl",
          phone: 56933892855,
        },
        {
          number: 3,
          status: true,
          student: "Melani Vivar",
          career: "ICI",
          mail: "melani.vivar@mail.udp.cl",
          phone: 56958364130,
        },
        {
          number: 4,
          status: true,
          student: "Jenifer Gonzalez",
          career: "OC",
          mail: "jenifer.gonzalez@mail.udp.cl",
          phone: 56979837599,
        },
        {
          number: 5,
          status: true,
          student: "Ayline Escobedo",
          career: "OC",
          mail: "ayline.escobedo@mail.udp.cl",
          phone: 56951150319,
        },
        {
          number: 6,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 7,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 8,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 9,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 10,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 11,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 12,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 13,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 14,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 15,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
      ],
    },
    {
      letter: "D",
      location: "Por Ejercito, segundo piso, al fondo.",
      slots: [
        {
          number: 1,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 2,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 3,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 4,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 5,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 6,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 7,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 8,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 9,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 10,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 11,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 12,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 13,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 14,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
        {
          number: 15,
          status: false,
          student: "",
          career: "",
          mail: "",
          phone: 569,
        },
      ],
    },
  ],
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between py-14 px-24 relative">
      <div className="absolute -z-10 inset-0 bg-fuchsia-400 bg-[size:20px_20px] opacity-5 blur-[100px]"></div>
      <div className="p-2 mb-8">
        <h1 className="text-4xl font-extrabold text-center">
          Facultad de Ingeniería y Ciencias
        </h1>
      </div>
      <Status data={data} />
      <div className="flex flex-col space-y-6">
        {data.lockers.map((locker, index) => (
          <div key={index} className="space-y-1">
            <div className="flex flex-col sm:flex-row sm:space-x-1">
              <h2>Ubicación:</h2>
              <p className="text-muted-foreground">{locker.location}</p>
            </div>
            <div
              key={index}
              className="min-w-72 grid gap-2 border-4 p-2 rounded-md grid-cols-2 sm:grid-cols-5"
            >
              {locker.slots.map((slot, index) => (
                <Locker key={index} letter={locker.letter} slot={slot} />
              ))}
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
